repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.29.0
    hooks:
      - id: yapf
        args: ["--style=style.yapf", "--in-place"]
